export const UI_COLORS = {
  startBgA: "#050913",
  startBgB: "#10203a",
  startBgC: "#05070d",
  previewBgA: "#08141f",
  previewBgB: "#04080d",
  gold: "#f1c40f",
  textLight: "#ecf0f1",
  infoBlue: "#3498db",
  success: "#2ecc71",
  danger: "#e74c3c",
  tipGray: "#95a5a6",
  accentOrange: "#f39c12",
  white: "white",
  transparentBlack: "rgba(0, 0, 0, 0)",
  vignette: "rgba(0, 0, 0, 0.62)",
  panelFill: "rgba(7, 13, 23, 0.86)",
  panelStroke: "rgba(241, 196, 15, 0.8)",
  panelAccent: "rgba(46, 204, 113, 0.55)",
  previewPanelFill: "rgba(10, 19, 30, 0.88)",
  previewPanelStroke: "rgba(46, 204, 113, 0.9)",
  previewMapFill: "rgba(5, 10, 16, 0.9)",
  previewMapStroke: "rgba(149, 165, 166, 0.45)",
  gameOverOverlay: "rgba(0, 0, 0, 0.8)",
  subtleText: "rgba(236, 240, 241, 0.78)",
  shadow: "rgba(0, 0, 0, 0.7)",
};

export const UI_LAYOUT = {
  halfRatio: 0.5,
  startPanelWidthRatio: 0.86,
  startPanelMaxWidth: 760,
  startPanelHeightRatio: 0.74,
  startPanelMaxHeight: 520,
  startPanelMinTopMargin: 20,
  previewPanelWidthRatio: 0.9,
  previewPanelMaxWidth: 860,
  previewPanelHeightRatio: 0.84,
  previewPanelMaxHeight: 620,
  startVignetteCenterYRatio: 0.45,
  startVignetteInnerRatio: 0.2,
  startVignetteOuterRatio: 0.7,
  titleYRatio: 0.16,
  subtitleYRatio: 0.23,
  sectionTopYRatio: 0.35,
  startCtaYRatio: 0.86,
  startTipYRatio: 0.92,
  previewTitleYRatio: 0.12,
  previewInfoYRatio: 0.18,
  previewMapYRatio: 0.22,
  previewMapHeightRatio: 0.56,
  previewCtaYRatio: 0.9,
  leftColumnXRatio: 0.12,
  rightColumnXRatio: 0.54,
  mapPaddingRatio: 0.08,
  mapPaddingMax: 64,
  lineSpacing1: 36,
  lineSpacing2: 68,
  lineSpacing3: 100,
  launchLabelXOffset: 44,
};

export const UI_FONT = {
  family: "sans-serif",
  bold: "bold",
  startTitle: { min: 30, max: 50, ratio: 0.072 },
  startSubtitle: { min: 14, max: 20, ratio: 0.03 },
  startSection: { min: 16, max: 22, ratio: 0.03 },
  startBody: { min: 13, max: 18, ratio: 0.022 },
  startTip: { min: 12, max: 16, ratio: 0.02 },
  startCta: { min: 18, max: 26, ratio: 0.035 },
  previewTitle: { min: 26, max: 44, ratio: 0.052 },
  previewInfo: { min: 13, max: 18, ratio: 0.022 },
  previewLabel: { min: 12, max: 16, ratio: 0.019 },
  previewCta: { min: 18, max: 24, ratio: 0.03 },
  gameOverTitle: "30px sans-serif",
  gameOverTime: "40px sans-serif",
  gameOverHint: "20px sans-serif",
};

export const UI_SHAPE = {
  panelRadius: 18,
  accentInset: 14,
  accentHeight: 6,
  accentRadius: 3,
  mapRadius: 12,
  markerRadius: 6,
  mapRouteWidth: 4,
  strokeWidth: 2,
  thinStrokeWidth: 1,
  shadowStrong: 10,
  shadowSoft: 5,
  shadowOff: 0,
  previewMaxPointsStep: 800,
  mapDrawPadding: 18,
};

export const UI_TEXT = {
  gameTitle: "AeroCarGame",
  startSubtitle: "TIME ATTACK",
  controlsTitle: "CONTROLES",
  controlsLeft: "<- ESQUERDA (segurar): Freio / ERS",
  controlsRight: "-> DIREITA (segurar): Boost",
  controlsTip: "Canto sup. direito / Z ou X: Alterna Modo",
  goalTitle: "OBJETIVO",
  goalLine1: "Conclua o trajeto em menor tempo",
  goalLine2: "equilibrando curvas e retas",
  goalTagline: "Novo regulamento F1 2026",
  startCta: "APERTE ESPACO OU CLIQUE PARA INICIAR",
  startFootnote: "Prepare-se: largada ao iniciar",
  previewTitle: "Preview da Pista",
  previewInfoTemplate:
    "Seed fixa {seed} | Segmentos {segments} | Volta {km} km",
  launchLabel: "Largada",
  previewCta: "APERTE ESPACO, ENTER OU CLIQUE PARA IR PARA A LARGADA",
  gameOverTitle: "FIM DE CORRIDA!",
  gameOverHint: "Aperte Espaço para tentar de novo",
};
